//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SanPham
    {
        public long Id { get; set; }
        public string TenSP { get; set; }
        public int LoaiSP { get; set; }
        public string Mota { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Hinh { get; set; }
    
        public virtual tbl_LoaiSanPham tbl_LoaiSanPham { get; set; }
    }
}
